### ISSUE TITLE
Feedback on page: /guides/v2.2/cloud/configure/configure-best-practices.html

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#2108]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [X] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

 We should add a store view example that is not tied to language.  For example, adding a brand with a different theme and that displays different products.

**Comment by jfrontain** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Cloud project.

**Comment by hguthrie** [comment]
This request is tracked in the Cloud kanban MAGECLOUD-2282.

**Comment by hguthrie** [comment]
Major updates to this section were made late last year. Closing out this issue.
