### ISSUE TITLE
Magento Cloud version schema confusion

### ISSUE THREAD

**Issue by ryantfowler** [magento/devdocs#2112]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [X] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other
 
## Description:
 It's unclear to me as a user of Magento Open Source and Commerce whether or not there's a dedicated Magento Cloud "Release Notes" section and/or if the version number schema for Magento Cloud is the same as Magento Commerce. [This](https://devdocs.magento.com/guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.6-2.1.11.html) is the best I can find for Magento Cloud Release Notes, but it leaves much to be desired. Again, I have zero idea if the Cloud versions directly correspond to Commerce versions or not.
  
## Expected result:
No ambiguity regarding Magento Cloud versions and Magento Cloud versions, and being able to efficiently find release notes relating to Magento Cloud.

## Possible solutions:
1. Provide a section with details as to how Magento Cloud versions correlate to Magento Commerce versions.
2. Potentially including Magento Cloud information [here](https://magento.com/resources/technical) or providing a snippet with a link to the appropriate Magento Cloud area where this can be found ( such as something on the https://cloud.magento.com, for example ).
 
## Additional information:
I understand the thrust of Magento Cloud is to provide an easy to use solution for merchants, but us code slingers have to set it up for them... so help us to help you ;).

Thank you

**Comment by jeff-matthews** [comment]
@ryantfowler, thanks for the feedback. You're right, release notes are confusing in this regard. Here's a little background that should help in the short-term.

Originally, we published release notes for **Cloud** alongside **Magento Open Source** and **Magento Commerce** as a "third" product class. That accounts for the link you shared above:

> https://devdocs.magento.com/guides/v2.1/cloud/release-notes/CloudReleaseNotes2.1.6-2.1.11.html

This was necessary because although Cloud uses the Commerce product, there was special Cloud tooling that was integrated with the Commerce release process.

After a while, the team responsible for Cloud development separated the core tooling that makes the cloud product unique (i.e., `ece-tools`) and started releasing updates based on a different semantic versioning schema (e.g., `2002.0.x`) and schedule. At that time, we started publishing separate release notes just for `ece-tools`. You can find that information in the Cloud guide on devdocs:

> https://devdocs.magento.com/guides/v2.2/cloud/composer-packages/ece-tools.html

I hope that helps clarify the current state of things. I definitely think we can do a better job explaining the difference between Commerce updates and `ece-tools` updates in the Cloud guide on devdocs. I'm assigning this to the writers responsible for the Cloud guide for further research (@hguthrie & @meker12).

**Comment by hguthrie** [comment]
Hi! @ryantfowler I agree with you and @jeff-matthews , and thank you for your feedback. We recognize how confusing the **Cloud tools** release information is and we have a project underway to clean the [Upgrades and patches](https://devdocs.magento.com/guides/v2.2/cloud/project/project-upgrade-parent.html) section of the Cloud guide. For this next release, there **will** be a sub-topic in this section called "Cloud tools release notes" located in the `/cloud/release-notes/cloud-tools.html` directory that focuses completely on the `ece-tools` updates. This is just the beginning, but I hope it helps.

**Comment by ryantfowler** [comment]
@jeff-matthews thank you for the feedback and background. I'll take a look at the links that you provided me. Is there any way you could provide me with an understanding of besides the core cloud tools (ece), if the remainder of the codebase is inline with the Commerce version?

Thank you

**Comment by ryantfowler** [comment]
@hguthrie thank you for acknowledging an opportunity for improvement in the documentation, and for sharing that there are improvements on their way. That is great news.

Thank you

**Comment by jeff-matthews** [comment]
@ryantfowler, the Cloud product runs Magento Commerce.

**Comment by ryantfowler** [comment]
@jeff-matthews thank you. That's one of the critical pieces of info I was looking for! Much obliged, Sir.

**Comment by jeff-matthews** [comment]
Happy to help!

**Comment by ryantfowler** [comment]
Closing this now as the devdocs now reflect a release notes section. Thanks
