### ISSUE TITLE
UI Component overview shows wrong method for execution

### ISSUE THREAD

**Issue by danmooney2** [magento/devdocs#2381]
## This issue is a:
- [x] Bug on the website
- [ ] New topic request
- [ ] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
https://devdocs.magento.com/guides/v2.3/ui_comp_guide/bk-ui_comps.html#javascript-class has this image:
https://devdocs.magento.com/common/images/ui_comp_js_class.png.  The execution method should be `initialize`, not `initialization`.

## Expected result:
"initialize" is seen as method for execution

**Comment by bdenham** [comment]
Closing this issue as it is being fixed in this PR: https://github.com/magento/devdocs/pull/2469
