### ISSUE TITLE
Feedback on page: /guides/v2.2/cloud/access-acct/fastly.html

### ISSUE THREAD

**Issue by dougkm** [magento/devdocs#2387]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [x] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

The section with the Origin Shield locations needs to also include the Cloud PaaS region to Shield locations mappings  for starter customers.

### Steps to reproduce

1. First Step
2. Second Step
3. Etc.

**Comment by meker12** [comment]
@dougkm  Apologies for the delayed response.  I created a [JIRA ticket](https://magento2.atlassian.net/browse/MAGECLOUD-2552) to provide info about Fastly setup for customers on the Cloud Starter plan. 

In the meantime, there's a KB article that explains [how to configure Fastly on Starter:](https://support.magento.com/hc/en-us/articles/360002491773-Set-up-Fastly-for-Starter-plan-on-Cloud):

Are you talking about using these Anycast IP's to configure Fastly service for the Cloud PaaS region to Shield location mappings for customers on the Starter plan

```To point your production domain to the Fastly service, follow these steps:

Add the domain name to your DNS record settings.
Point the domain to the Fastly CNAME or Anycast IP's.
The Fastly CNAME is prod.magentocloud.map.fastly.net; Anycast IP's are:

151.101.1.124
151.101.65.124
151.101.129.124
151.101.193.124 
```

**Comment by jfrontain** [comment]
We are re-organizing our unresolved GH issues into smaller, more focused projects, and have moved this to the Cloud project.

**Comment by meker12** [comment]
Addresses added here: https://devdocs.magento.com/cloud/cdn/configure-fastly.html#dns
