### ISSUE TITLE
Incorrect information on page: guides/v2.2/cloud/basic-information/cloud-plans.html

### ISSUE THREAD

**Issue by jaustinlam** [magento/devdocs#2395]
## This issue is a:
- [ ] Bug on the website
- [ ] New topic request
- [ X] Topic clarification request
- [ ] New DevDocs feature request
- [ ] Other

## Description:
This page states that BI Essentials is only available for Cloud Pro, it is also available on Cloud Starter. The AWS Managed VPN Connection Service access is not currently offered for either plan.

### Steps to reproduce

1. First Step
2. Second Step
3. Etc.

**Comment by hguthrie** [comment]
Thanks for pointing this out. Created an internal ticket to fix this issue.

**Comment by hguthrie** [comment]
Changes were approved and merged this morning.
